### ISSUE TITLE
Does not work on ubuntu 13.10.

### ISSUE THREAD

**Issue by anilgulecha** [jianli/git-playback#2]
Installed via :

```
 $sudo pip install git-playback
[sudo] password for anil: 
Downloading/unpacking git-playback
  Downloading git-playback-0.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/git-playback/setup.py) egg_info for package git-playback

Downloading/unpacking gitpython (from git-playback)
  Downloading GitPython-0.1.7.tar.gz
  Running setup.py (path:/tmp/pip_build_root/gitpython/setup.py) egg_info for package gitpython

Installing collected packages: git-playback, gitpython
  Running setup.py install for git-playback

    Installing git-playback script to /usr/local/bin
  Running setup.py install for gitpython

Successfully installed git-playback gitpython
Cleaning up...
```

And then going a git playback <file> gives:

```
$ git playback Gemfile
Traceback (most recent call last):
  File "/usr/local/bin/git-playback", line 9, in <module>
    load_entry_point('git-playback==0.1', 'console_scripts', 'git-playback')()
  File "/usr/local/lib/python2.7/dist-packages/playback/__init__.py", line 145, in playback
    except git.exc.GitCommandError as err:
AttributeError: 'module' object has no attribute 'exc'
```
